# Generated by Django 4.2.1 on 2023-05-16 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
        ('thread', '0002_alter_thread_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='community.community'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='title',
            field=models.CharField(max_length=512),
        ),
    ]
